---
version: '3.8'

services:
  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one:1.19
    ports: 
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  prometheus:
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports: 
      - 9090:9090
  keycloak:
    hostname: keycloak
    image: jboss/keycloak
    ports: 
      - 81:8080
    environment:
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: password 
  inventory:
    hostname: inventory
    image: javahippie/mp-demo-inventory:0.1.0
    ports:
      - 83:9080
  pricing:
    hostname: pricing
    image: javahippie/mp-demo-pricing:0.1.0
    ports:
      - 82:9080

networks:
  front:
      driver: bridge
  back:
      driver: overlay 
