global:
  scrape_interval: 15s

  external_labels:
    monitor: 'jax-monitor'

scrape_configs:
  - job_name: 'pricing'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pricing:9080']
  - job_name: 'inventory'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory:9080']
