global:
  scrape_interval: 15s

  external_labels:
    monitor: 'jax-monitor'

scrape_configs:
  - job_name: 'pricing'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9080']
